copyright: 'This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.<br/>Kx and kdb+ are registered trademarks of <a href="https://kx.com">Kx Systems, Inc.</a>, a subsidiary of <a href="http://www.firstderivatives.com/">First Derivatives plc</a>.'
# dev_addr: '159.65.88.218:8000'
dev_addr: '0.0.0.0:9001'
docs_dir: 'docs'
extra_css: 
  - 'stylesheets/extra.css'
  - 'stylesheets/prism.css'
extra_javascript: 
  # See /syntax/#projection to see if MathJax is working 
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'https://code.jquery.com/jquery-3.1.1.min.js'
  # - 'https://tracker.mrpfd.com/tracker.js'
  - 'https://use.fontawesome.com/releases/v5.2.0/js/all.js'
  # theme.js modifies HTML to prepare for prism.js
  - 'scripts/theme.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.4.0/clipboard.min.js'
  # Prism script includes plugin Copy to Clipboard http://prismjs.com/download.html
  # Omits plugins Command Line, Line highlight, and Line Numbers: no effect
  - 'scripts/prism.js'
google_analytics:
  - 'UA-3462586-1'
  - 'auto'
markdown_extensions:
  - admonition
  # - codehilite(guess_lang=false)
  - extra
  # - fenced_code
  # - fontawesome_markdown
  - pymdownx.arithmatex
  # - pymdownx.betterem(smart_enable=all)
  # - pymdownx.caret
  # - pymdownx.critic
  # - pymdownx.emoji:
  # emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  # - pymdownx.smartsymbols
  # - pymdownx.superfences
  # - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - toc:
      permalink: true
plugins: 
  - search
  # - markdownextradata
remote_branch: 'master'
repo_name: 'GitHub'
repo_url: 'https://github.com/StephenTaylor-Kx/phrases'
site_dir: 'site'
site_author: 'Kx Systems'
site_description: "Q expressions for common tasks"
site_name: "Q Phrasebook"
site_url: 'http://code.kx.com/phrases'
use_directory_urls: true
theme: 
  custom_dir: theme/
  favicon: ./img/favicon.ico
  # feature:
  #   tabs: true
  name: 'material'
  logo: 'img/kx.jpeg'
  palette: 
    primary: 'blue'
    accent: 'deep orange'
  toc:
    title: "On this page"
nav:
  - Q Reference: 'https://code.kx.com/v2/ref'
  - Introduction: introduction.md
  - Index: index.md
  - Casting: cast.md
  - Math: math.md
  - Merge: merge.md
  - Miscellaneous: misc.md
  - Sublists: sublists.md
  - Sorts: sorts.md
  - Original wiki page: wikipage.md