# Q Phrasebook
copyright: 'This work is licensed under a <a rel="license" href="https://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.<br/>KX and kdb+ are registered trademarks of <a href="https://kx.com">Kx Systems, Inc.</a>, a subsidiary of FD Technologies plc</a>.'

dev_addr: 'localhost:9001'

extra_css: 
  - 'stylesheets/2021.css'
  - 'stylesheets/prism.css'

extra_javascript: 
  - 'scripts/prism.js'
  - 'scripts/theme.js'
  # MathJax scripts
  - 'scripts/mathjax.js' # configure MathJax object
  - 'scripts/polyfill.min.js'
  - 'scripts/tex-mml-chtml.js'

google_analytics:
  - 'UA-3462586-1'
  - 'auto'

markdown_extensions:
  - admonition
  - attr_list
  - extra
  - pymdownx.arithmatex
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.tilde
  - toc:
      permalink: true

remote_branch: 'master'
repo_name: 'kxcontrib/phrases'
repo_url: 'https://github.com/kxcontrib/phrases'

site_author: 'Kx Systems'
site_dir: 'site'
site_description: "Q expressions for common tasks"
site_name: "Q Phrasebook"
site_url: 'https://code.kx.com/phrases/'

theme: 
  custom_dir: theme
  favicon: 'https://code.kx.com/2021.ico'
  font: false
  name: 'material'
  language: en
  logo: img/kx.png
  palette: 
    accent: 'blue'
    primary: 'black'
    scheme: default
  static_templates:
    - 404.html

use_directory_urls: true

nav:
  - Introduction: intro.md
  - Index: index.md
  - Arithmetic: arith.md
  - Casting: cast.md
  - Execution: exec.md
  - Finance: fin.md
  - Find: find.md
  - Flags: flag.md
  - Format: form.md
  - Geometry: trig.md
  - Indexes: indexes.md
  - Math: math.md
  - Matrixes: matrix.md
  - Miscellaneous: misc.md
  - Parts and items: part.md
  - Polynomials: poly.md
  - Rank: rank.md
  - Shape: shape.md
  - Sort: sort.md
  - Statistics: stat.md
  - Strings: string.md
  - Temporal: temp.md
  - Tests: test.md
  - Text: text.md
  - phrases.q: phrases.md
  - on style: style.md
  - index to QIdioms: index2.md
  - QIdioms: wikipage.md
  - kdb+ and q: "https://code.kx.com/q/"
  - Kx Systems: "https://kx.com"
  