site_name: "Q Phrasebook"
site_url: 'https://code.kx.com/phrases/'
copyright: 'This work is licensed under a <a rel="license" href="https://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.<br/>Kx and kdb+ are registered trademarks of <a href="https://kx.com">Kx Systems, Inc.</a>, a subsidiary of <a href="https://www.firstderivatives.com/">First Derivatives plc</a>.'
dev_addr: 'localhost:9001'
extra_css: 
  - 'https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/themes/prism-solarizedlight.min.css'
  - 'https://code.kx.com/stylesheets/extra.css'
extra_javascript: 
  # Omits plugins Command Line, Line highlight, and Line Numbers: no effect
  # Prism script includes plugin Copy to Clipboard http://prismjs.com/download.html
  - 'https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.4.0/clipboard.min.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'https://code.jquery.com/jquery-3.5.1.min.js'
  - 'https://code.kx.com/scripts/prism.js'
  - scripts/theme.js
google_analytics:
  - 'UA-3462586-1'
  - 'auto'
markdown_extensions:
  - admonition
  - attr_list
  - extra
  - pymdownx.arithmatex
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.tilde
  - toc:
      permalink: true
remote_branch: 'master'
repo_name: 'kxcontrib/phrases on GitHub'
repo_url: 'https://github.com/kxcontrib/phrases'
site_dir: 'site'
site_author: 'Kx Systems'
site_description: "Q expressions for common tasks"
theme: 
  favicon: ./img/favicon.ico
  name: 'material'
  logo: 'img/kx.jpeg'
  palette: 
    primary: 'blue'
    accent: 'deep orange'
use_directory_urls: true
nav:
  - Introduction: intro.md
  - Index: index.md
  - Arithmetic: arith.md
  - Casting: cast.md
  - Execution: exec.md
  - Finance: fin.md
  - Find: find.md
  - Flags: flag.md
  - Format: form.md
  - Geometry: trig.md
  - Indexes: indexes.md
  - Math: math.md
  - Matrixes: matrix.md
  - Miscellaneous: misc.md
  - Parts and items: part.md
  - Polynomials: poly.md
  - Rank: rank.md
  - Shape: shape.md
  - Sort: sort.md
  - Statistics: stat.md
  - Strings: string.md
  - Temporal: temp.md
  - Tests: test.md
  - Text: text.md
  - phrases.q: phrases.md
  - on style: style.md
  - index to QIdioms: index2.md
  - QIdioms: wikipage.md
  - kdb+ and q: "https://code.kx.com/q/"
  - Kx Systems: "https://kx.com"
  